### ISSUE TITLE
Framework to be used

### ISSUE THREAD

**Issue by Tishasoumya-02** [AADI-1331/glassmorphism-template#2]
The project will be restricted to HTML, CSS, or some frameworks can be used here?

**Comment by AADI-1331** [comment]
sorry, I didn't get you can u explain in detail.

**Comment by Tishasoumya-02** [comment]
Like could bootstrap, tailwind CSS, etc frameworks could be used?

**Comment by AADI-1331** [comment]
Tisha u can use anything.

**Comment by Tishasoumya-02** [comment]
Ok, just add hacktoberfest topic to the repo I would be happy to contribute :)

**Comment by AADI-1331** [comment]
Added

**Comment by Tishasoumya-02** [comment]
I would like to work on the flip cards if you could assign me this issue in the Assignees section it would be great! 😄

**Comment by AADI-1331** [comment]
ok

**Comment by Tishasoumya-02** [comment]
Only the 4 images which you have shown in the demo repo has to be used right?

**Comment by AADI-1331** [comment]
If u mean flip cards then you have to remove that 3 game cards and instead of this you have to placed that flip cards in a manner that 1 row contains 4 cards and if someone add 5 th one ,it will goes to 2nd🙂

**Comment by Tishasoumya-02** [comment]
Understood✌
