### ISSUE TITLE
Wireframe in figma.

### ISSUE THREAD

**Issue by Pranavanbu28** [AADI-1331/glassmorphism-template#23]
I would like to create a cool prototype for this flipcards page using figma.

**Comment by Pranavanbu28** [comment]
Please do assign this issue to me and kindly add the hacktoberfest label to it.

**Comment by AADI-1331** [comment]
assigned bro, go for it

**Comment by Pranavanbu28** [comment]
Bro kindly add the hacktoberfest label to this issue

**Comment by Pranavanbu28** [comment]
@AADI-1331 bro small letters hacktoberfest label.

**Comment by AADI-1331** [comment]
the label is already taken

**Comment by AADI-1331** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/78849620/135573960-18183990-e8ce-4661-98c4-757684825906.png)
can u figure it out this error

**Comment by Pranavanbu28** [comment]
what is the problem?

**Comment by AADI-1331** [comment]
nothing now it is solved

**Comment by AADI-1331** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/78849620/135578611-e37f287e-3acf-475a-81f3-1f9970e6ab11.png)
this links are not flexing when its tab is minimised

**Comment by Pranavanbu28** [comment]
bro can I do anything regarding glassmorphic design or should I exactly like how it is in this image?

**Comment by AADI-1331** [comment]
what exactly u want to change
