### ISSUE TITLE
Adding search icon

### ISSUE THREAD

**Issue by Garima-7** [AADI-1331/glassmorphism-template#29]
![Untitled](https://user-images.githubusercontent.com/83363645/135728379-def2a3ba-cf90-44fe-ae3f-579770a367b6.png)
The search box is not having any placeholder.
So adding search icon will give this unique view.
Assign this issue to me.

**Comment by AADI-1331** [comment]
Coooool

**Comment by AADI-1331** [comment]
Can u give purple and red gradient to placeholder.👍

**Comment by Garima-7** [comment]
> Can u give purple and red gradient to placeholder.👍

yaa sure.

**Comment by coder483** [comment]
is this issue solved or not

**Comment by AADI-1331** [comment]
> is this issue solved or not

Which one?
