### ISSUE TITLE
Improvement of navbar

### ISSUE THREAD

**Issue by Garima-7** [AADI-1331/glassmorphism-template#5]
![Screenshot (446)](https://user-images.githubusercontent.com/83363645/135292879-93b126e8-4bae-4377-9fc0-d0826b6f35a9.png)
Improving navbar and making it look alike template.

**Comment by Garima-7** [comment]
can I work on this issue under hacktoberfest?

**Comment by AADI-1331** [comment]
sure

**Comment by AADI-1331** [comment]
yes u can

**Comment by Abhicoder03** [comment]
Hi @AADI-1331, Could you please assign this to me under hacktoberfest.

**Comment by Garima-7** [comment]
![Screenshot (447)](https://user-images.githubusercontent.com/83363645/135422551-c6074631-99fb-4f39-89e4-09931a212eca.png)
Is it fine now?

**Comment by AADI-1331** [comment]
can u send a short clip of this
it will help to understand better

**Comment by Garima-7** [comment]
https://user-images.githubusercontent.com/83363645/135472509-b95b0658-69ce-4e0e-912a-ac02bbadec7b.mp4

short clip of navbar

**Comment by AADI-1331** [comment]
ya fine
I'll merge it

**Comment by AADI-1331** [comment]
![error](https://user-images.githubusercontent.com/78849620/135496574-271dbf5d-6db9-4547-8141-dadc2dabedb1.png)
have u changes the links css.

**Comment by Garima-7** [comment]
I have not made PR for this yet.
I was about to make it at night bcoz hacktoberfest merged pr's will be counted from 1 oct.

**Comment by AADI-1331** [comment]
i am happy and confused at same time

**Comment by AADI-1331** [comment]
I
![Screenshot (682)](https://user-images.githubusercontent.com/78849620/135501036-7400a334-691c-416f-af40-e12987f3126a.png)
 and my group of 180 friends started pulling and merging requests

**Comment by AADI-1331** [comment]
> I have not made PR for this yet. I was about to make it at night bcoz hacktoberfest merged pr's will be counted from 1 Oct.

take ur time

**Comment by Garima-7** [comment]
> I ![Screenshot (682)](https://user-images.githubusercontent.com/78849620/135501036-7400a334-691c-416f-af40-e12987f3126a.png) and my group of 180 friends started pulling and merging requests

But as mentioned on hacktoberfest website only pr's merged in october will be considered.

**Comment by AADI-1331** [comment]
where

**Comment by AADI-1331** [comment]
can u give a screenshot

**Comment by Garima-7** [comment]
![Screenshot (448)](https://user-images.githubusercontent.com/83363645/135504061-75698005-77f2-4871-b273-2e5c6bb34b7b.png)
In the FAQ section

**Comment by AADI-1331** [comment]
it's fine but see the chat
in discord

**Comment by Garima-7** [comment]
No problem, I will make PR after 12 at night.
Don't want any confusion in head.
Hope you understand.
