### ISSUE TITLE
can i add tailwind css?

### ISSUE THREAD

**Issue by apoorvcodes** [AADI-1331/glassmorphism-template#7]
tailwind css can be a great asset, and can help a lot of devs to connect to the repo cause lot of devs prefer tailwind now days

**Comment by apoorvcodes** [comment]
would be a simple pr from my side

**Comment by AADI-1331** [comment]
u can use anything

**Comment by apoorvcodes** [comment]
so after adding can i do a pull request?

**Comment by AADI-1331** [comment]
yes bro sure
I'll merge it

**Comment by AADI-1331** [comment]
should i assign u

**Comment by apoorvcodes** [comment]
yea sure

**Comment by apoorvcodes** [comment]
ill pull it tommorow

**Comment by AADI-1331** [comment]
ya ur, wish buddy I said many of my friends to do it today and I'll be merging it as soon as the event will start.

**Comment by AADI-1331** [comment]
but sure you can put tom.

**Comment by apoorvcodes** [comment]
can you assign me pls, for this task?

**Comment by AADI-1331** [comment]
yes

**Comment by apoorvcodes** [comment]
Fixed and added tailwindcss #12

**Comment by AADI-1331** [comment]
![error](https://user-images.githubusercontent.com/78849620/135497320-25e913f6-550c-4563-ae9c-5c4c58a9fb01.png)
error on flexing
